- name: Retrieve Elasticsearch internal user passwords
  shell: "/data/elasticsearch-8.7.0/bin/elasticsearch-setup-passwords auto --batch --url https://localhost:9200"
  register: elasticsearch_password_output
  ignore_errors: true

- name: Print Elasticsearch internal user passwords
  debug:
    msg: "{{ elasticsearch_password_output.stdout_lines }}"

#- name: Install "curl"
  #apt:
    #name: curl
    #state: present

- name: Set Elasticsearch password for the elastic user
  set_fact:
    elasticsearch_password: "{{ elasticsearch_password_output.stdout | regex_search('PASSWORD elastic = (.*)', '\\1') }}"
    

#- name: Retrieve Kibana enrollment token
  #uri:
    #url: "https://localhost:9200/_security/enrollment_token"
    #method: POST
    #body_format: json
    #body: '{"type": "kibana"}'
    #user: elastic
    #password: "{{ elasticsearch_password }}"
    #client_cert: /data/elasticsearch-8.7.0/config/certs/http.p12
    #client_key: /data/elasticsearch-8.7.0/config/certs/http.p12
    #validate_certs: no
    #headers:
      #Content-Type: "application/json"
    #return_content: yes
  #register: kibana_enrollment_token_output
  #ignore_errors: true

#- name: Print Kibana enrollment token
  #debug:
    #msg: "{{ kibana_enrollment_token_output.json.token }}"
